### ISSUE TITLE
Vote class

### ISSUE THREAD

**Issue by durid17** [Open-Sorcery/elector_lib#1]
Create Vote class , capable of creating new vote, and registering it via Elector API.

**Comment by lkito** [comment]
I'd like to write this one

**Comment by lkito** [comment]
Can you tell me which file I need to write it in and what functionality the class needs to have?

**Comment by durid17** [comment]
you should write it in `elector_lib/elector_lib.py. ` , Vote class should have methods, `vote` --request vote , `status_code` return stratus_code and `data` return response data
